# Устанавливаем стандартные версси для языков, это гарантирует,
# что хуки будут выполнены на указанной версии языка, если
# для конкретного хука версия языка не указана отдельно
default_language_version:
  python: python3.10

# Список репозиториев, содержащих хуки pre-commit, которые
# мы хотим заиспользовать.
# ВАЖНО: порядок имеет значение. Хуки будут исполнены в том
# порядке, в котором они перечисленны ниже
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Проверяет (только) корректность форматирования YAML
      - id: check-yaml
      # Проверяет (только) корректность форматирования JSON
      - id: check-json
      # Проверяет что мы случайно не добавили большие файлы
      - id: check-added-large-files
      # Проверка того, что в каждом файле в конце есь
      # пустая строка (автоматически добавляет там где нет)
      - id: end-of-file-fixer
      # Автоматически удаляет лишние пробелы в конце строки
      - id: trailing-whitespace
      # Проверяет (только) наличие конфликтов в регистре
      # в именах файлов. P.S. есть ОС чувствительные и не
      # чувствительные к регистру, например myfile.txt и
      # MyFile.txt могут быть как разными так и одинаковыми
      - id: check-case-conflict
      # Проверяет и исправляет наличие смешанных концов строк
      # P.S. в разных ОС приняты разные символы для
      # обозначения конца строки в текстовых файлвх
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      # Является основным хуком для Black. Будет применен
      # ко всем .py и .pyi файлам
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      # Основной хук для isort (сортировщик импортов)
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # Дополнительные зависимости для flake8.
        # Для примера используем bugbear, позволяющий найти
        # те учаски кода, которые потенциально содержат баги
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      # Запускает форматтер Black на jupyter notebooks
      - id: nbqa-black
        additional_dependencies: [black==23.3.0]
      # Запускает isort на jupyter notebooks
      - id: nbqa-isort
        additional_dependencies: [isort==5.12.0]
      # Запускает flake8 на jupyter notebooks
      - id: nbqa-flake8
        additional_dependencies: [flake8==6.0.0]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        # Типы файлов, на которых должен выполняться хук
        types_or: [markdown, yaml, toml, json, shell]
        additional_dependencies:
          # Дополнительные зависимости для хука prettier
          ["prettier@2.8.8", "prettier-plugin-sh@0.13.0-alpha.1"]
        # Аргументы для команды prettier
        args: [--print-width=80, --prose-wrap=always]
